export const teamNameToCode: { [name: string]: string } = {
  "Mexico": "MEX",
  "South Africa": "RSA",
  "South Korea": "KOR",
  "Czech Republic": "CZE",
  "Canada": "CAN",
  "Bosnia & Herzegovina": "BIH",
  "Qatar": "QAT",
  "Switzerland": "SUI",
  "Brazil": "BRA",
  "Morocco": "MAR",
  "Haiti": "HAI",
  "Scotland": "SCO",
  "USA": "USA",
  "Paraguay": "PAR",
  "Australia": "AUS",
  "Turkey": "TUR",
  "Germany": "GER",
  "Curaçao": "CUW",
  "Ivory Coast": "CIV",
  "Ecuador": "ECU",
  "Netherlands": "NED",
  "Japan": "JPN",
  "Sweden": "SWE",
  "Tunisia": "TUN",
  "Belgium": "BEL",
  "Egypt": "EGY",
  "Iran": "IRN",
  "New Zealand": "NZL",
  "Spain": "ESP",
  "Cape Verde": "CPV",
  "Saudi Arabia": "KSA",
  "Uruguay": "URU",
  "France": "FRA",
  "Senegal": "SEN",
  "Iraq": "IRQ",
  "Norway": "NOR",
  "Argentina": "ARG",
  "Algeria": "ALG",
  "Austria": "AUT",
  "Jordan": "JOR",
  "Portugal": "POR",
  "DR Congo": "COD",
  "Uzbekistan": "UZB",
  "Colombia": "COL",
  "England": "ENG",
  "Croatia": "CRO",
  "Ghana": "GHA",
  "Panama": "PAN"
};

export const teamCodeToPortuguese: { [code: string]: string } = {
  MEX: "México",
  RSA: "África do Sul",
  KOR: "Coreia do Sul",
  CZE: "República Tcheca",
  CAN: "Canadá",
  BIH: "Bósnia",
  QAT: "Catar",
  SUI: "Suíça",
  BRA: "Brasil",
  MAR: "Marrocos",
  HAI: "Haiti",
  SCO: "Escócia",
  USA: "Estados Unidos",
  PAR: "Paraguai",
  AUS: "Austrália",
  TUR: "Turquia",
  GER: "Alemanha",
  CUW: "Curaçao",
  CIV: "Costa do Marfim",
  ECU: "Equador",
  NED: "Holanda",
  JPN: "Japão",
  SWE: "Suécia",
  TUN: "Tunísia",
  BEL: "Bélgica",
  EGY: "Egito",
  IRN: "Irã",
  NZL: "Nova Zelândia",
  ESP: "Espanha",
  CPV: "Cabo Verde",
  KSA: "Arábia Saudita",
  URU: "Uruguai",
  FRA: "França",
  SEN: "Senegal",
  IRQ: "Iraque",
  NOR: "Noruega",
  ARG: "Argentina",
  ALG: "Argélia",
  AUT: "Áustria",
  JOR: "Jordânia",
  POR: "Portugal",
  COD: "RD Congo",
  UZB: "Uzbequistão",
  COL: "Colômbia",
  ENG: "Inglaterra",
  CRO: "Croácia",
  GHA: "Gana",
  PAN: "Panamá"
};

export function translateTeam(name: string): { name: string; code: string } {
  const code = teamNameToCode[name] || "UNK";
  const ptName = teamCodeToPortuguese[code] || name;
  return { name: ptName, code };
}
